### ISSUE TITLE
ECDYSIS Taxonomy help - Alcides (Coleoptera) vs. Alcides (Lepidoptera)

### ISSUE THREAD

**Issue by genevieve-anderegg** [Symbiota/community-board#574]
I have noticed an issue with the generic name _Alcides_ being attributed to both a genus within Coleoptera, and a genus within Lepidoptera. I noticed this when I downloaded a backup file of our records (DMNS-Entomology) and filtered by Coleoptera because I wanted to know how many families of beetles we had databased specimens for, and a couple of butterflies showed up on the list.

In the backup, catalog numbers ZE.118986 and ZE.118987 both have values of Order=Coleoptera, but Family=Uraniidae. Uraniidae is a family in Lepidoptera. It looks like the confusion comes from the genus of the butterflies, _Alcides_, which has been used in both Lepidoptera (https://www.gbif.org/species/1954074, https://en.wikipedia.org/wiki/Alcides) and Coleoptera, Curculionidae (https://www.gbif.org/species/1186651). The cuculionid genus is considered "Doubtful" by GBIF taxonomy.

There are a ton of species within the weevil genus in Ecdysis, and I don't want to go mucking about with the shared taxonomy too much in case other folks are using it. But I would like my uraniid butterflies to correctly come up under Lepidoptera.
 Could I have some help untangling this all please? Thanks!

**Comment by themerekat** [comment]
Hi @genevieve-anderegg , alas, Symbiota portals don't handle homonyms super well, which gets tricky in taxonomically diverse portals. My best advice is that we change one of the genera (probably the more "doubtful" one) to include the author inside the scientific name string, so that it can be distiguished from the Lepidopteran genus. That will also involve making sure that the correct name is associated with all the Alcides specimens, but it looks like there are only 3 specimens, so I don't foresee this being a big problem.

**Comment by themerekat** [comment]
@genevieve-anderegg , I created this taxon: https://ecdysis.org/taxa/taxonomy/taxoneditor.php?tid=1645565 and re-mapped your butterflies to it. Sorry we don't have a better system for dealing with this messiness!

**Comment by genevieve-anderegg** [comment]
Thank you so much for your help Katie! Sounds good, I'll follow this example if I run across any other instances of homonyms. Cheers!
